//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Zbu.ModelsBuilder alpha
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;

namespace Zbu.ModelsBuilder.Tests.Models
{
    // Content Type 1044 with alias "page"
    public partial class Page : PublishedContentModel
    {
        public Page(IPublishedContent content)
            : base(content)
        { }

        public string UmbracoUrlName
        {
            get { return this.GetPropertyValue<string>("umbracoUrlName"); }
        }

        public int UmbracoInternalRedirectId
        {
            get { return this.GetPropertyValue<int>("umbracoInternalRedirectId"); }
        }

        public int UmbracoRedirect
        {
            get { return this.GetPropertyValue<int>("umbracoRedirect"); }
        }

        public string PageKey
        {
            get { return this.GetPropertyValue<string>("pageKey"); }
        }

        public object Mntp1
        {
            get { return this.GetPropertyValue("mntp1"); }
        }

        public object Mntp2
        {
            get { return this.GetPropertyValue("mntp2"); }
        }
    }

    // Content Type 1059 with alias "AnotherPage"
    public partial class AnotherPage : PublishedContentModel
    {
        public AnotherPage(IPublishedContent content)
            : base(content)
        { }

        public string UmbracoUrlAlias
        {
            get { return this.GetPropertyValue<string>("umbracoUrlAlias"); }
        }

        public string Nothing
        {
            get { return this.GetPropertyValue<string>("nothing"); }
        }
    }

    // Content Type 1068 with alias "loskDalmosk"
    public partial class LoskDalmosk : PublishedContentModel
    {
        public LoskDalmosk(IPublishedContent content)
            : base(content)
        { }
    }

    // Content Type 2078 with alias "parentDoc"
    public partial class ParentDoc : PublishedContentModel
    {
        public ParentDoc(IPublishedContent content)
            : base(content)
        { }

        public string Prop1
        {
            get { return this.GetPropertyValue<string>("prop1"); }
        }
    }

    // Content Type 2079 with alias "childDoc"
    public partial class ChildDoc : ParentDoc
    {
        public ChildDoc(IPublishedContent content)
            : base(content)
        { }

        public string Prop2
        {
            get { return this.GetPropertyValue<string>("prop2"); }
        }
    }

    // Content Type 2087 with alias "aaa"
    public partial class Aaa : ParentDoc
    {
        public Aaa(IPublishedContent content)
            : base(content)
        { }
    }

    // Content Type 2091 with alias "CrazyCTypeAlias"
    public partial class CrazyCTypeAlias : PublishedContentModel
    {
        public CrazyCTypeAlias(IPublishedContent content)
            : base(content)
        { }
    }

    // Content Type 4092 with alias "RtePage"
    public partial class RtePage : PublishedContentModel
    {
        public RtePage(IPublishedContent content)
            : base(content)
        { }

        public IHtmlString Rte
        {
            get { return this.GetPropertyValue<IHtmlString>("rte"); }
        }

        public IHtmlString SimpleText
        {
            get { return this.GetPropertyValue<IHtmlString>("simpleText"); }
        }
    }

    // Content Type 5101 with alias "SubRtePage"
    public partial class SubRtePage : RtePage
    {
        public SubRtePage(IPublishedContent content)
            : base(content)
        { }
    }

    // Content Type 6104 with alias "bbb"
    public partial class SpecialBbb : ParentDoc, IMixinTestRenamed
    {
        public SpecialBbb(IPublishedContent content)
            : base(content)
        { }

        public string MixinProp
        {
            get { return this.GetPropertyValue<string>("MixinProp"); }
        }
    }

    // Mixin content Type 6105 with alias "MixinTest"
    public partial interface IMixinTestRenamed : IPublishedContent
    {
        string MixinProp { get; }
    }

    // Content Type 6105 with alias "MixinTest"
    public partial class MixinTestRenamed : PublishedContentModel, IMixinTestRenamed
    {
        public MixinTestRenamed(IPublishedContent content)
            : base(content)
        { }

        public string MixinProp
        {
            get { return this.GetPropertyValue<string>("MixinProp"); }
        }
    }
}


