using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using NUnit.Framework;
using Umbraco.Core.Composing;
using Umbraco.Core.Configuration.UmbracoSettings;
using ZpqrtBnk.ModelsBuilder.Api;
using ZpqrtBnk.ModelsBuilder.Building;
using ZpqrtBnk.ModelsBuilder.Configuration;

namespace ZpqrtBnk.ModelsBuilder.Tests
{
    [TestFixture]
    public class CustomBuilderTests
    {
        [SetUp]
        public void Setup()
        {
            Current.Reset();
            Current.UnlockConfigs();
            Current.Configs.Add(() => new Config());
            Current.Configs.Add<IUmbracoSettingsSection>(() => new UmbracoSettingsSection());
        }

        [Test]
        public void CustomNames()
        {
            var type1 = new TypeModel
            {
                Id = 1,
                Alias = "type1",
                ParentId = 0,
                BaseType = null,
                ItemType = TypeModel.ItemTypes.Content,
            };
            type1.Properties.Add(new PropertyModel
            {
                Alias = "prop1",
                ModelClrType = typeof(string),
            });

            var types = new[] { type1 };

            var code = new Dictionary<string, string>
            {
                {"assembly", @"
using ZpqrtBnk.ModelsBuilder;
"}
            };

            var refs = new[]
            {
                MetadataReference.CreateFromFile(typeof (string).Assembly.Location),
                MetadataReference.CreateFromFile(typeof (ReferencedAssemblies).Assembly.Location)
            };

            var parseResult = new CodeParser().Parse(code, refs);
            var builder = new CustomNamesBuilder(types, parseResult);
            var btypes = builder.AllTypeModels;

            var sb = new StringBuilder();
            builder.WriteContentTypeModel(sb, builder.GetContentTypeModels().First());
            var gen = sb.ToString();

            var version = ApiVersion.Current.Version;
            var expected = @"//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    ZpqrtBnk.ModelsBuilder v" + version + @"
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using ZpqrtBnk.ModelsBuilder;
using ZpqrtBnk.ModelsBuilder.Umbraco;
using System.CodeDom.Compiler;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Provides extension methods for the Type1Custom class.</summary>
	public static partial class Type1CustomExtensions
	{
		[GeneratedCodeAttribute(MB.Name, MB.VersionString)]
		public static string Prop1(this Type1Custom that, Fallback fallback = default, string defaultValue = default)
			=> that.Value<string>(""prop1"", fallback: fallback, defaultValue: defaultValue);
	}

	[PublishedModel(""type1"")]
	public partial class Type1Custom : PublishedContentModel
	{
		// ctor
		public Type1Custom(IPublishedContent content)
			: base(content)
		{ }

		// properties

		[GeneratedCodeAttribute(MB.Name, MB.VersionString)]
		[ImplementPropertyType(""prop1"")]
		public string Prop1 => this.Prop1();
	}
}
";
            Console.WriteLine(gen);
            Assert.AreEqual(expected.ClearLf(), gen);
        }

        private class CustomNamesBuilder : Builder
        {
            public CustomNamesBuilder(IList<TypeModel> typeModels, ParseResult parseResult) 
                : base(typeModels, parseResult)
            { }

            public CustomNamesBuilder(IList<TypeModel> typeModels, ParseResult parseResult, string modelsNamespace) 
                : base(typeModels, parseResult, modelsNamespace)
            { }

            public override string GetClrName(TypeModel typeModel)
            {
                return base.GetClrName(typeModel) + "Custom";
            }
        }
    }
}
