using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Umbraco.Core.Composing;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web.PropertyEditors;
using ZpqrtBnk.ModelsBuilder.Api;
using ZpqrtBnk.ModelsBuilder.Configuration;

namespace ZpqrtBnk.ModelsBuilder.Building
{
    /// <summary>
    /// Implements a builder that works by writing text.
    /// </summary>
    internal class TextBuilder : Builder
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextBuilder"/> class with a list of models to generate
        /// and the result of code parsing.
        /// </summary>
        /// <param name="typeModels">The list of models to generate.</param>
        /// <param name="parseResult">The result of code parsing.</param>
        public TextBuilder(IList<TypeModel> typeModels, ParseResult parseResult)
            : base(typeModels, parseResult)
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="TextBuilder"/> class with a list of models to generate,
        /// the result of code parsing, and a models namespace.
        /// </summary>
        /// <param name="typeModels">The list of models to generate.</param>
        /// <param name="parseResult">The result of code parsing.</param>
        /// <param name="modelsNamespace">The models namespace.</param>
        public TextBuilder(IList<TypeModel> typeModels, ParseResult parseResult, string modelsNamespace)
            : base(typeModels, parseResult, modelsNamespace)
        { }

        // internal for unit tests only
        internal TextBuilder()
        { }

        #region Append Helpers

        private int _indent = 0;

        private string Indent => new string('\t', _indent);

        private void IndentEnter() { _indent++; }

        private void IndentExit() { _indent--; }

        private string NewLine => "\n";

        private void AppendLine(StringBuilder sb, string text)
        {
            for (var i = 0; i < _indent; i++)
                sb.Append('\t');
            sb.Append(text);
            sb.Append(NewLine);
        }

        private void AppendNewLine(StringBuilder sb)
        {
            sb.Append(NewLine);
        }

        public void AppendBetween(StringBuilder stringBuilder, ref bool first, string text)
        {
            if (first)
                first = false;
            else
                stringBuilder.Append(text);
        }

        public void AppendNewLineBetween(StringBuilder stringBuilder, ref bool first)
        {
            AppendBetween(stringBuilder, ref first, NewLine);
        }

        // writes an attribute that identifies code generated by a tool
        // (helps reduce warnings, tools such as FxCop use it)
        // see https://github.com/zpqrtbnk/Zbu.ModelsBuilder/issues/107
        // see https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.generatedcodeattribute
        // see https://blogs.msdn.microsoft.com/codeanalysis/2007/04/27/correct-usage-of-the-compilergeneratedattribute-and-the-generatedcodeattribute/
        //
        // note that the blog post above clearly states that "Nor should it be applied at the type level if the type being generated is a partial class."
        // and since our models are partial classes, we have to apply the attribute against the individual members, not the class itself.
        //
        private void AppendGeneratedCodeAttribute(StringBuilder sb)
        {
            var mbName = ParseResult.MBClassName;
            AppendLine(sb, $"[GeneratedCodeAttribute({mbName}.Name, {mbName}.VersionString)]");
        }

        private void AppendLocalGeneratedCodeAttribute(StringBuilder sb)
        {
            AppendLine(sb, "[GeneratedCodeAttribute(Name, VersionString)]");
        }

        #endregion

        /// <summary>
        /// Outputs a generated model to a string builder.
        /// </summary>
        /// <param name="sb">The string builder.</param>
        /// <param name="typeModel">The model to generate.</param>
        public void Generate(StringBuilder sb, TypeModel typeModel)
        {
            WriteHeader(sb);

            foreach (var t in TypesUsing)
                AppendLine(sb, $"using {t};");
            if (!TypesUsing.Contains("System.CodeDom.Compiler"))
                AppendLine(sb, "using System.CodeDom.Compiler;");

            AppendNewLine(sb);
            AppendLine(sb, $"namespace {GetModelsNamespace()}");
            AppendLine(sb, "{");
            IndentEnter();

            AppendContentTypeModel(sb, typeModel);

            IndentExit();
            AppendLine(sb, "}");
        }

        /// <summary>
        /// Outputs generated models to a string builder.
        /// </summary>
        /// <param name="sb">The string builder.</param>
        /// <param name="typeModels">The models to generate.</param>
        public void Generate(StringBuilder sb, IEnumerable<TypeModel> typeModels)
        {
            WriteHeader(sb);

            foreach (var t in TypesUsing)
                AppendLine(sb, $"using {t};");
            if (!TypesUsing.Contains("System.CodeDom.Compiler"))
                AppendLine(sb, "using System.CodeDom.Compiler;");

            // assembly attributes marker
            AppendNewLine(sb);
            AppendLine(sb, "//ASSATTR");

            AppendNewLine(sb);
            AppendLine(sb, $"namespace {GetModelsNamespace()}");
            AppendLine(sb, "{");
            IndentEnter();

            foreach (var typeModel in typeModels)
            {
                AppendContentTypeModel(sb, typeModel);
                AppendNewLine(sb);
            }

            IndentExit();
            AppendLine(sb, "}");
        }

        #region Header

        /// <summary>
        /// Outputs an "auto-generated" header to a string builder.
        /// </summary>
        /// <param name="sb">The string builder.</param>
        public static void WriteHeader(StringBuilder sb)
        {
            TextHeaderWriter.WriteHeader(sb);
        }

        #endregion

        #region Meta

        /// <summary>
        /// Appends Meta.
        /// </summary>
        /// <param name="sb">The string builder.</param>
        /// <param name="typeModels">The models to generate.</param>
        public void AppendMeta(StringBuilder sb, IEnumerable<TypeModel> typeModels)
        {
            var typeModelsList = typeModels.ToList();
            var mbName = ParseResult.MBClassName;

            WriteHeader(sb);

            //AppendLine(sb, "// ReSharper disable All");
            //AppendNewLine(sb);

            AppendLine(sb, "using System.CodeDom.Compiler;");
            AppendLine(sb, "using Umbraco.Core.Models.PublishedContent;");
            AppendLine(sb, "using ZpqrtBnk.ModelsBuilder.Umbraco;");

            AppendNewLine(sb);
            AppendLine(sb, $"namespace {GetModelsNamespace()}");
            AppendLine(sb, "{");
            IndentEnter();

            AppendLine(sb, "/// <summary>Models Builder</summary>");
            AppendLine(sb, $"public static partial class {mbName}");
            AppendLine(sb, "{");
            IndentEnter();

            AppendLine(sb, "/// <summary>Gets Models Builder's generator name.</summary>");
            AppendLine(sb, "public const string Name = \"ZpqrtBnk.ModelsBuilder\";");
            AppendNewLine(sb);

            AppendLine(sb, "/// <summary>Gets the Models Builder version that was used to generate the files.</summary>");
            AppendLine(sb, $"public const string VersionString = \"{ApiVersion.Current.Version}\";");
            AppendNewLine(sb);

            AppendMetaItemTypes(sb, typeModelsList);
            AppendNewLine(sb);

            AppendMetaContentTypeAliases(sb, typeModelsList);
            AppendNewLine(sb);

            AppendMetaPropertyTypeAliases(sb, typeModelsList);
            AppendNewLine(sb);

            AppendContentTypes(sb, typeModelsList);
            AppendNewLine(sb);

            AppendPropertyTypes(sb, typeModelsList);
            AppendNewLine(sb);

            AppendMetaModels(sb, typeModelsList);

            IndentExit();
            AppendLine(sb, "}"); // MB class

            IndentExit();
            AppendLine(sb, "}"); // namespace
        }

        private void AppendMetaItemTypes(StringBuilder sb, IEnumerable<TypeModel> typeModels)
        {
            AppendLine(sb, "/// <summary>Provides the content type published item types.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, "public static class ItemType");
            AppendLine(sb, "{");
            IndentEnter();

            var firstType = true;
            foreach (var typeModel in typeModels)
            {
                AppendNewLineBetween(sb, ref firstType);
                AppendMetaItemType(sb, typeModel);
            }

            IndentExit();
            AppendLine(sb, "}");
        }

        private void AppendMetaItemType(StringBuilder sb, TypeModel typeModel)
        {
            AppendLine(sb, $"/// <summary>Gets the published item type of the {typeModel.ClrName} content type.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, $"public const PublishedItemType {typeModel.ClrName} = PublishedItemType.{typeModel.ItemType.ToPublishedItemType()};");
        }

        private void AppendMetaContentTypeAliases(StringBuilder sb, IEnumerable<TypeModel> typeModels)
        {
            AppendLine(sb, "/// <summary>Defines the content type alias constants.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, "public static class ContentAlias");
            AppendLine(sb, "{");
            IndentEnter();

            var firstType = true;
            foreach (var typeModel in typeModels)
            {
                AppendNewLineBetween(sb, ref firstType);
                AppendMetaContentTypeAlias(sb, typeModel);
            }

            IndentExit();
            AppendLine(sb, "}");
        }

        private void AppendMetaContentTypeAlias(StringBuilder sb, TypeModel typeModel)
        {
            AppendLine(sb, $"/// <summary>Gets the alias of the {typeModel.ClrName} content type.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, $"public const string {typeModel.ClrName} = \"{typeModel.Alias}\";");
        }

        private void AppendMetaPropertyTypeAliases(StringBuilder sb, IEnumerable<TypeModel> typeModels)
        {
            AppendLine(sb, "/// <summary>Defines the property type alias constants.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, "public static class PropertyAlias");
            AppendLine(sb, "{");
            IndentEnter();

            var firstType = true;
            foreach (var typeModel in typeModels)
            {
                AppendNewLineBetween(sb, ref firstType);
                AppendMetaPropertyTypeAliases(sb, typeModel);
            }

            IndentExit();
            AppendLine(sb, "}");
        }

        private void AppendMetaPropertyTypeAliases(StringBuilder sb, TypeModel typeModel)
        {
            AppendLine(sb, $"/// <summary>Defines the property type alias constants for the {typeModel.ClrName} content type.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, $"public static class {typeModel.ClrName}");
            AppendLine(sb, "{");
            IndentEnter();

            var firstProperty = true;
            foreach (var propertyModel in typeModel.Properties)
            {
                AppendNewLineBetween(sb, ref firstProperty);
                AppendMetaPropertyTypeAlias(sb, typeModel, propertyModel);
            }

            IndentExit();
            AppendLine(sb, "}");
        }

        private void AppendMetaPropertyTypeAlias(StringBuilder sb, TypeModel typeModel, PropertyModel propertyModel)
        {
            AppendLine(sb, $"/// <summary>Gets the alias of the {typeModel.ClrName}.{propertyModel.ClrName} property type.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, $"public const string {propertyModel.ClrName} = \"{propertyModel.Alias}\";");
        }

        private void AppendContentTypes(StringBuilder sb, IEnumerable<TypeModel> typeModels)
        {
            AppendLine(sb, "/// <summary>Provides the content types.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, "public static class ContentType");
            AppendLine(sb, "{");
            IndentEnter();

            var firstType = true;
            foreach (var typeModel in typeModels)
            {
                AppendNewLineBetween(sb, ref firstType);
                AppendContentType(sb, typeModel);
            }

            IndentExit();
            AppendLine(sb, "}");
        }

        private void AppendContentType(StringBuilder sb, TypeModel typeModel)
        {
            AppendLine(sb, $"/// <summary>Gets the {typeModel.ClrName} content type.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, $"public static readonly IPublishedContentType {typeModel.ClrName} = PublishedModelUtility.GetModelContentType(ItemType.{typeModel.ClrName}, \"{typeModel.Alias}\");");
        }

        private void AppendPropertyTypes(StringBuilder sb, IEnumerable<TypeModel> typeModels)
        {
            AppendLine(sb, "/// <summary>Provides the property types.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, "public static class PropertyType");
            AppendLine(sb, "{");
            IndentEnter();

            var firstType = true;
            foreach (var typeModel in typeModels)
            {
                AppendNewLineBetween(sb, ref firstType);
                AppendPropertyTypes(sb, typeModel);
            }

            IndentExit();
            AppendLine(sb, "}");
        }

        private void AppendPropertyTypes(StringBuilder sb, TypeModel typeModel)
        {
            AppendLine(sb, $"/// <summary>Provides the property types for the {typeModel.ClrName} content type.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, $"public static class {typeModel.ClrName}");
            AppendLine(sb, "{");
            IndentEnter();

            var firstProperty = true;
            foreach (var propertyModel in typeModel.Properties)
            {
                AppendNewLineBetween(sb, ref firstProperty);
                AppendPropertyType(sb, typeModel, propertyModel);
            }

            IndentExit();
            AppendLine(sb, "}");
        }

        private void AppendPropertyType(StringBuilder sb, TypeModel typeModel, PropertyModel propertyModel)
        {
            AppendLine(sb, $"/// <summary>Gets the {typeModel.ClrName}.{propertyModel.ClrName} property type.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, $"public static readonly IPublishedPropertyType {propertyModel.ClrName} = ContentType.{typeModel.ClrName}.GetPropertyType(PropertyAlias.{typeModel.ClrName}.{propertyModel.ClrName});");
        }

        private void AppendMetaModels(StringBuilder sb, IEnumerable<TypeModel> typeModels)
        {
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, "private readonly ContentTypeModelInfo[] _models = ");
            AppendLine(sb, "{");
            IndentEnter();

            var firstType = true;
            foreach (var typeModel in typeModels)
            {
                AppendBetween(sb, ref firstType, $",{NewLine}");

                sb.Append(Indent);
                sb.Append($"new ContentTypeModelInfo(\"{typeModel.Alias}\", \"{typeModel.ClrName}\", typeof(");
                AppendClrType(sb, typeModel.ClrName);
                sb.Append(")");
                if (typeModel.Properties.Count > 0)
                {
                    sb.Append(",");
                    AppendNewLine(sb);
                    IndentEnter();
                    var firstProperty = true;
                    foreach (var propertyModel in typeModel.Properties)
                    {
                        AppendBetween(sb, ref firstProperty, $",{NewLine}");
                        sb.Append(Indent);
                        sb.Append($"new PropertyTypeModelInfo(\"{propertyModel.Alias}\", \"{propertyModel.ClrName}\", typeof(");
                        AppendClrType(sb, propertyModel.ClrTypeName);
                        sb.Append("))");
                    }
                    IndentExit();
                }

                sb.Append(")");
            }
            AppendNewLine(sb);

            IndentExit();
            AppendLine(sb, "};");

            AppendNewLine(sb);
            AppendLine(sb, "/// <summary>Gets the model infos.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, "public IReadOnlyCollection<ContentTypeModelInfo> Models => _models;");

            AppendNewLine(sb);
            AppendLine(sb, "/// <summary>Gets the model infos for a content type.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, "public ContentTypeModelInfo Model(string alias) => _models.FirstOrDefault(x => x.Alias == alias);");

            AppendNewLine(sb);
            AppendLine(sb, "/// <summary>Gets the model infos for a content type.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, "public ContentTypeModelInfo Model<TModel>() => _models.FirstOrDefault(x => x.ClrType == typeof(TModel));");

            AppendNewLine(sb);
            AppendLine(sb, "/// <summary>Gets the model infos for a content type.</summary>");
            AppendLocalGeneratedCodeAttribute(sb);
            AppendLine(sb, "public ContentTypeModelInfo Model(Type typeofModel) => _models.FirstOrDefault(x => x.ClrType == typeofModel);");
        }

        #endregion

        #region Models

        private void AppendContentTypeModel(StringBuilder sb, TypeModel type)
        {
            // generate interface for mixins
            if (type.IsMixin)
            {
                AppendMixinInterface(sb, type);
                AppendNewLine(sb);
            }

            AppendExtensionMethods(sb, type);
            AppendNewLine(sb);

            AppendClassDeclaration(sb, type);

            // begin class body
            AppendLine(sb, "{");
            IndentEnter();

            // write the ctor
            if (!type.HasCtor)
                AppendConstructor(sb, type);

            if (!type.HasCtor && ParseResult.GeneratePropertyGetters)
                AppendNewLine(sb);

            // write the properties
            if (ParseResult.GeneratePropertyGetters)
                AppendPropertyImplementations(sb, type);

            // close the class declaration
            IndentExit();
            AppendLine(sb, "}");
        }

        private void AppendMixinInterface(StringBuilder sb, TypeModel typeModel)
        {
            // write the interface declaration
            AppendLine(sb, $"// Mixin Content Type with alias \"{typeModel.Alias}\"");
            if (!string.IsNullOrWhiteSpace(typeModel.Name))
                AppendLine(sb, $"/// <summary>{XmlCommentString(typeModel.Name)}</summary>");
            sb.Append($"{Indent}public partial interface I{typeModel.ClrName}");

            var implements = typeModel.BaseType == null || typeModel.BaseType.IsContentIgnored
                ? (typeModel.HasBase ? null : (typeModel.IsElement ? "PublishedElement" : "PublishedContent"))
                : typeModel.BaseType.ClrName;

            if (implements != null)
                sb.Append($" : I{implements}");

            // write the mixins
            var sep = implements == null ? ":" : ",";
            foreach (var mixinType in typeModel.DeclaringInterfaces.OrderBy(x => x.ClrName))
            {
                sb.Append($"{sep} I{mixinType.ClrName}");
                sep = ",";
            }

            AppendNewLine(sb);
            AppendLine(sb, "{");
            IndentEnter();

            // write the properties - only the local (non-ignored) ones, we're an interface
            var firstProperty = true;
            foreach (var propertyModel in typeModel.Properties.Where(x => !x.IsIgnored).OrderBy(x => x.ClrName))
            {
                AppendNewLineBetween(sb, ref firstProperty);
                AppendInterfaceProperty(sb, propertyModel);
            }

            IndentExit();
            AppendLine(sb, "}");
        }

        private void AppendExtensionMethods(StringBuilder sb, TypeModel typeModel)
        {
            // write extension methods for properties
            var extensionProperties = typeModel.Properties.Where(x => !x.IsIgnored && !x.IsExtensionImplemented).ToList();
            if (extensionProperties.Count == 0) return;

            AppendLine(sb, $"/// <summary>Provides extension methods for the {(typeModel.IsMixin ? "I" : "")}{typeModel.ClrName} {(typeModel.IsMixin ? "interface" : "class")}.</summary>");
            AppendLine(sb, $"public static partial class {typeModel.ClrName}Extensions");

            AppendLine(sb, "{");
            IndentEnter();

            var firstProperty = true;
            foreach (var propertyModel in extensionProperties)
            {
                AppendNewLineBetween(sb, ref firstProperty);
                AppendExtensionMethod(sb, typeModel, propertyModel);
            }

            IndentExit();
            AppendLine(sb, "}");
        }

        private void AppendClassDeclaration(StringBuilder sb, TypeModel typeModel)
        {
            if (typeModel.IsRenamed)
                AppendLine(sb, $"// Content Type with alias \"{typeModel.Alias}\"");

            if (!string.IsNullOrWhiteSpace(typeModel.Name))
                AppendLine(sb, "/// <summary>{XmlCommentString(typeModel.Name)}</summary>");

            // cannot do it now. see note in ImplementContentTypeAttribute
            //if (!type.HasImplement)
            //    sb.AppendFormat("\t[ImplementContentType(\"{0}\")]\n", type.Alias);

            AppendLine(sb, $"[PublishedModel(\"{typeModel.Alias}\")]");
            sb.Append($"{Indent}public partial class {typeModel.ClrName}");

            var inherits = typeModel.HasBase
                ? null // has its own base already
                : (typeModel.BaseType == null || typeModel.BaseType.IsContentIgnored
                    ? GetBaseClassName(typeModel)
                    : typeModel.BaseType.ClrName);

            if (inherits != null)
                sb.Append($" : {inherits}");

            var sep = inherits == null ? ":" : ",";
            if (typeModel.IsMixin)
            {
                // if it's a mixin it implements its own interface
                sb.Append($"{sep} I{typeModel.ClrName}");
            }
            else
            {
                // write the mixins, if any, as interfaces
                // only if not a mixin because otherwise the interface already has them already
                foreach (var mixinType in typeModel.DeclaringInterfaces.OrderBy(x => x.ClrName))
                {
                    sb.Append($"{sep} I{mixinType.ClrName}");
                    sep = ",";
                }
            }

            AppendNewLine(sb);
        }

        private void AppendConstructor(StringBuilder sb, TypeModel typeModel)
        {
            AppendLine(sb, "// ctor");
            AppendLine(sb, $"public {typeModel.ClrName}(IPublished{(typeModel.IsElement ? "Element" : "Content")} content)");
            IndentEnter();
            AppendLine(sb, $": base(content)");
            IndentExit();
            AppendLine(sb, "{ }");
        }

        private void AppendPropertyImplementations(StringBuilder sb, TypeModel type)
        {
            AppendLine(sb, "// properties");

            // write the properties
            foreach (var prop in type.Properties.Where(x => !x.IsIgnored).OrderBy(x => x.ClrName))
                AppendPropertyImplementation(sb, prop);

            // no need to write the parent properties since we inherit from the parent
            // and the parent defines its own properties. need to write the mixins properties
            // since the mixins are only interfaces and we have to provide an implementation.

            // write the mixins properties
            foreach (var mixinType in type.ImplementingInterfaces.OrderBy(x => x.ClrName))
                foreach (var prop in mixinType.Properties.Where(x => !x.IsIgnored).OrderBy(x => x.ClrName))
                {
                    // exclude directly implemented properties
                    if (type.IgnoredMixinProperties.Contains(prop)) continue;
                    AppendPropertyImplementation(sb, prop);
                }
        }

        private void AppendExtensionMethod(StringBuilder sb, TypeModel typeModel, PropertyModel propertyModel)
        {
            if (propertyModel.Errors != null) return;

            // Adds xml summary to each property containing
            // property name and property description
            if (!string.IsNullOrWhiteSpace(propertyModel.Name) || !string.IsNullOrWhiteSpace(propertyModel.Description))
            {
                var summary = XmlCommentString(propertyModel.Name);
                if (!string.IsNullOrWhiteSpace(propertyModel.Description))
                    summary += ": " + XmlCommentString(propertyModel.Description);

                AppendLine(sb, $"/// <summary>{summary}</summary>");
            }

            AppendGeneratedCodeAttribute(sb);

            sb.Append(Indent);
            sb.Append("public static ");
            AppendClrType(sb, propertyModel.ClrTypeName);
            sb.Append(" ");
            sb.Append(propertyModel.ClrName);
            sb.AppendFormat("(this {0}{1} that", typeModel.IsMixin ? "I" : "", typeModel.ClrName);
            if (propertyModel.VariesByCulture())
                sb.Append(", string culture = null");
            if (propertyModel.VariesBySegment())
                sb.Append(", string segment = null");
            sb.Append(", Fallback fallback = default, string defaultValue = default)");
            sb.Append(NewLine);
            IndentEnter();
            sb.Append(Indent);
            sb.Append("=> that.Value");
            if (propertyModel.ModelClrType != typeof(object))
            {
                sb.Append("<");
                AppendClrType(sb, propertyModel.ClrTypeName);
                sb.Append(">");
            }
            sb.AppendFormat("(\"{0}\"", propertyModel.Alias);
            if (propertyModel.VariesByCulture())
                sb.Append(", culture: culture");
            if (propertyModel.VariesBySegment())
                sb.Append(", segment: segment");
            sb.Append(", fallback: fallback, defaultValue: defaultValue);");
            sb.Append(NewLine);
            IndentExit();
        }

        private void AppendPropertyImplementation(StringBuilder sb, PropertyModel property)
        {
            AppendNewLine(sb);

            if (property.Errors != null)
                AppendPropertyErrorsStart(sb, property.Errors);

            // Adds xml summary to each property containing
            // property name and property description
            if (!string.IsNullOrWhiteSpace(property.Name) || !string.IsNullOrWhiteSpace(property.Description))
            {
                var summary = XmlCommentString(property.Name);
                if (!string.IsNullOrWhiteSpace(property.Description))
                    summary += ": " + XmlCommentString(property.Description);

                AppendLine(sb, $"/// <summary>{summary}</summary>");
            }

            AppendGeneratedCodeAttribute(sb);
            AppendLine(sb, $"[ImplementPropertyType(\"{property.Alias}\")]");
            sb.Append(Indent);
            sb.Append("public ");
            AppendClrType(sb, property.ClrTypeName);
            sb.Append($" {property.ClrName} => this.{property.ClrName}();");
            AppendNewLine(sb);

            if (property.Errors != null)
                AppendPropertyErrorsEnd(sb);
        }

        private void AppendInterfaceProperty(StringBuilder sb, PropertyModel property)
        {
            if (property.Errors != null)
                AppendPropertyErrorsStart(sb, property.Errors);

            if (!string.IsNullOrWhiteSpace(property.Name))
                sb.AppendFormat("\t\t/// <summary>{0}</summary>\n", XmlCommentString(property.Name));

            AppendGeneratedCodeAttribute(sb);
            sb.Append(Indent);
            AppendClrType(sb, property.ClrTypeName);
            sb.Append($" {property.ClrName} {{ get; }}");
            AppendNewLine(sb);

            if (property.Errors != null)
                AppendPropertyErrorsEnd(sb);
        }

        private void AppendPropertyErrorsStart(StringBuilder sb, IEnumerable<string> errors)
        {
            AppendLine(sb, "/*");
            AppendLine(sb, " * THIS PROPERTY CANNOT BE IMPLEMENTED, BECAUSE:");
            AppendLine(sb, " *");

            IEnumerable<string> SplitError(string error)
            {
                var p = 0;
                while (p < error.Length)
                {
                    var n = p + 50;
                    while (n < error.Length && error[n] != ' ') n++;
                    if (n >= error.Length) break;
                    yield return error.Substring(p, n - p);
                    p = n + 1;
                }
                if (p < error.Length)
                    yield return error.Substring(p);
            }

            var first = true;
            foreach (var error in errors)
            {
                if (first) first = false;
                else AppendLine(sb, " *");
                foreach (var s in SplitError(error))
                {
                    AppendLine(sb, " *" + s);
                }
            }
            AppendLine(sb, " *");
            AppendNewLine(sb);
            AppendLine(sb, " *");
            AppendLine(sb, " */");
        }

        private void AppendPropertyErrorsEnd(StringBuilder sb)
        {
            AppendNewLine(sb);
        }

        #endregion

        #region CLR Types

        // internal for tests
        internal void AppendClrType(StringBuilder sb, Type type)
        {
            var s = type.ToString();

            if (type.IsGenericType)
            {
                var p = s.IndexOf('`');
                AppendNonGenericClrType(sb, s.Substring(0, p));
                sb.Append("<");
                var args = type.GetGenericArguments();
                for (var i = 0; i < args.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    AppendClrType(sb, args[i]);
                }
                sb.Append(">");
            }
            else
            {
                AppendNonGenericClrType(sb, s);
            }
        }

        // internal for tests
        internal void AppendClrType(StringBuilder sb, string type)
        {
            var p = type.IndexOf('<');
            if (type.Contains('<'))
            {
                AppendNonGenericClrType(sb, type.Substring(0, p));
                sb.Append("<");
                var args = type.Substring(p + 1).TrimEnd('>').Split(','); // fixme will NOT work with nested generic types
                for (var i = 0; i < args.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    AppendClrType(sb, args[i]);
                }
                sb.Append(">");
            }
            else
            {
                AppendNonGenericClrType(sb, type);
            }
        }

        private void AppendNonGenericClrType(StringBuilder sb, string s)
        {
            // map model types
            s = Regex.Replace(s, @"\{(.*)\}\[\*\]", m => ModelsMap[m.Groups[1].Value + "[]"]);

            // takes care eg of "System.Int32" vs. "int"
            if (TypesMap.TryGetValue(s, out var typeName))
            {
                sb.Append(typeName);
                return;
            }

            // if full type name matches a using clause, strip
            // so if we want Umbraco.Core.Models.IPublishedContent
            // and using Umbraco.Core.Models, then we just need IPublishedContent
            // also works for the models namespace
            typeName = s;
            string typeUsing = null;
            var p = typeName.LastIndexOf('.');
            if (p > 0)
            {
                var x = typeName.Substring(0, p);
                if (Using.Contains(x) || x == ModelsNamespace)
                {
                    typeName = typeName.Substring(p + 1);
                    typeUsing = x;
                }
            }

            // nested types *after* using
            typeName = typeName.Replace("+", ".");

            // symbol to test is the first part of the name
            // so if type name is Foo.Bar.Nil we want to ensure that Foo is not ambiguous
            p = typeName.IndexOf('.');
            var symbol = p > 0 ? typeName.Substring(0, p) : typeName;

            // what we should find - WITHOUT any generic <T> thing - just the type
            // no 'using' = the exact symbol
            // a 'using' = using.symbol
            var match = typeUsing == null ? symbol : (typeUsing + "." + symbol);

            // if not ambiguous, be happy
            if (!IsAmbiguousSymbol(symbol, match))
            {
                sb.Append(typeName);
                return;
            }

            // symbol is ambiguous
            // if no 'using', must prepend global::
            if (typeUsing == null)
            {
                sb.Append("global::");
                sb.Append(s.Replace("+", "."));
                return;
            }

            // could fullname be non-ambiguous?
            // note: all-or-nothing, not trying to segment the using clause
            typeName = s.Replace("+", ".");
            p = typeName.IndexOf('.');
            symbol = typeName.Substring(0, p);
            match = symbol;

            // still ambiguous, must prepend global::
            if (IsAmbiguousSymbol(symbol, match))
                sb.Append("global::");

            sb.Append(typeName);
        }

        private static readonly IDictionary<string, string> TypesMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "System.Int16", "short" },
            { "System.Int32", "int" },
            { "System.Int64", "long" },
            { "System.String", "string" },
            { "System.Object", "object" },
            { "System.Boolean", "bool" },
            { "System.Void", "void" },
            { "System.Char", "char" },
            { "System.Byte", "byte" },
            { "System.UInt16", "ushort" },
            { "System.UInt32", "uint" },
            { "System.UInt64", "ulong" },
            { "System.SByte", "sbyte" },
            { "System.Single", "float" },
            { "System.Double", "double" },
            { "System.Decimal", "decimal" }
        };

        #endregion

        private static string XmlCommentString(string s)
        {
            return s.Replace('<', '{').Replace('>', '}').Replace('\r', ' ').Replace('\n', ' ');
        }
    }
}
